### ISSUE TITLE
Program shutting down unexpectedly.

### ISSUE THREAD

**Issue by alimukhtar53** [vrushangdev/CodeWithMosh-dl#1]
Program is running fine but when it comes to exercise file like .zip file that is not .mp4 file, program stops & closes automatically and when i try to run program again it checks headers & at that point it stops itself and now i'm stuck at specific point can't jump to next file. Please fix this issue

**Comment by vrushangdev** [comment]
> Program is running fine but when it comes to exercise file like .zip file that is not .mp4 file, program stops & closes automatically and when i try to run program again it checks headers & at that point it stops itself and now i'm stuck at specific point can't jump to next file. Please fix this issue

 **can you share more info regarding it ? maybe share a screen shot**

**Comment by vrushangdev** [comment]
### **Issue Fixed** @jhonny53
